@videogame_api_HostAddress = http://localhost:5030
###

GET {{videogame_api_HostAddress}}/api/videogames/
Accept: application/xml

###

POST {{videogame_api_HostAddress}}/api/Videogames/
Content-Type: application/json

{
  "name": "Super Mario Bros",
  "description": "A classic platformer game",
  "platform": "NES"
}

###

@id=1
PUT {{videogame_api_HostAddress}}/api/videogames/{{id}}
Content-Type: application/json

{
  "name": "Resident Evil 8",
  "description": "A modern survival horror classic",
  "platform": "Multiple"
}

###

PATCH {{videogame_api_HostAddress}}/api/videogames/{{id}}
Content-Type: application/json

[
    {
    "op": "add",
    "path": "/name",
    "value": "Resident Evil 8: Village"
  }
]

###
